# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: backend action cd

on:
  workflow_call:
  

jobs:

 automerge:  
    if: contains('${{github.ref_name}}', 'develop')
    runs-on: ubuntu-latest
    steps:
      - name: execute merge
        uses: "gsoc2/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_PULLREQ }}"
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_METHOD: "merge"
          PULL_REQUEST: "${{ github.event.pull_request.number }}"
          LOG: "DEBUG"
 pull-request:
    needs: automerge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: git remote add origin https://github.com/hdteck/test_back.git
        continue-on-error: true    
      - run: git add -A
      - run: git config --global user.email "user@github.es"
      - run: git config --global user.name "github[bot]"
      - run: git commit --message 'primer commit a develop'
        continue-on-error: true 
      - run: git push --force-with-lease origin develop
        continue-on-error: true
      - name: pull-request
        run: gh pr create -B main -H develop --title 'PR to develop' --body 'PullRequest numero -> ${{github.ref_name}}'
        env:
              GH_TOKEN: "${{ vars.TOKEN_PULLREQ }}"