# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 'backend hotfix'

on:
  workflow_dispatch:


jobs:
  checkout: 
    if: contains('${{github.ref_name}}', 'hotfix')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "hotfix"
      - run: git add -A
      - run: git config --global user.email "user@github.es"
      - run: git config --global user.name "github[bot]"
      - run: git commit --message 'hotfix a develop'
        continue-on-error: true 
      - run: git push --force-with-lease hotfix develop
        continue-on-error: true
    
  automerge:
    needs: 'checkout'
    if: contains('${{github.ref_name}}', 'hotfix')
    runs-on: ubuntu-latest
    steps:
      - name: execute merge
        uses: "gsoc2/automerge-action@v0.16.2"
        with:
          ref: "hotfix"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_PULLREQ }}"
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_METHOD: "merge"
          PULL_REQUEST: "${{ github.event.pull_request.number }}"
          LOG: "DEBUG"
  edit-last-release:
    needs: 'automerge'
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "hotfix"
      - name: "Set latest tag"
        id: set-latest-tag
        run:  |
         echo "latest_tag=$(git tag | tail -n1)" >> $GITHUB_ENV 
        shell: bash
      
      - name: Edit Release
        uses: irongut/EditRelease@v1.2.0
        with:
            token: ${{ secrets.TOKEN_PULLREQ }}
            id: "157921768"
            name: "Hotfix ${{ env.latest_tag }}"
            prerelease: false
            body: "añadidos hotfixes."
            files: "changelog.md"