# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: backend action cd

on:
  workflow_call:
  

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_PULLREQ }}"
        with:
          source_branch: "main"                                 # If blank, default: triggered branch
          destination_branch: "develop"                      # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: ""                                      # Full markdown support, requires pr_title to be set
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: "diillson,worker"                         # Comma-separated list (no spaces)
          pr_assignee: "diillson,worker"                         # Comma-separated list (no spaces)
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_milestone: "Milestone 1"                       # Milestone name no Required it is comment
          pr_draft: true                                    # Creates pull request as draft
          pr_allow_empty: true                              # Creates pull request even if there are no changes


 
  automerge:
    needs: 'pull-request'
    if: contains('${{github.ref_name}}', 'develop')
    runs-on: ubuntu-latest
    steps:
      - name: execute merge
        uses: "gsoc2/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_PULLREQ }}"
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_METHOD: "rebase"
          PULL_REQUEST: "${{ github.event.pull_request.number }}"
          LOG: "DEBUG"
